In [1]:
import numpy as np

In [2]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
print(x)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [6]:
y = np.array([[0],[0],[0],[1]])
synapse0 = np.random.random((2,1))
synapse0

array([[0.88409285],
       [0.7734539 ]])

In [7]:
bias = 0.3
lr = 0.6
def nlinear(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [8]:
for i in range(100000):
    layer0 = x
    layer1 = nlinear(np.dot(layer0,synapse0)+bias)
    layer1_error = y-layer1
    layer1_delta = layer1_error*nlinear(layer1,True)
    synapse0 += np.dot(layer0.T,layer1_delta)
    synapse0 = synapse0*lr
    bias += lr*layer1_delta

In [9]:
print(layer1)

[[0.00290377]
 [0.00290378]
 [0.00290378]
 [0.99709636]]
